frontend/controllers/AgendaController.php
<?php

namespace frontend\controllers;

class AgendaController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionDetails()
    {
    	return $this->render('details');
    }

}

frontend/controllers/BeritaController.php
<?php

namespace frontend\controllers;

use Yii;

class BeritaController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionDetails()
    {
    	return $this->render('details');
    }

}

frontend/controllers/GaleriController.php
<?php

namespace frontend\controllers;

class GaleriController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionProfil()
    {
        return $this->render('profil');
    }

    public function actionKontak()
    {
        return $this->render('kontak');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link rel="icon" type="text/css" href="<?php echo Yii::getAlias('@depan');?>/tema/images/logo.png">
    <meta name="author" content="ardi-PC">
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
    <header id="header">
        <div class="container">
            <a href="<?php echo Yii::$app->homeUrl;?>" id="logo" title="Himpunan Mahasiswa Sistem Pembangkit Energi">Himpunan Mahasiswa Sistem Pembangkit Energi</a>
            <div class="menu-trigger"></div>
            <nav id="menu">
                <ul>
                    <li><?php echo Html::a('Profil', ['site/profil']);?></li>
                    <li><?php echo Html::a('Berita', ['berita/index']);?></li>
                    <li><?php echo Html::a('Agenda', ['agenda/index']);?></li>
                </ul>
                <ul>
                    <li><?php echo Html::a('Akademik', ['akademik/index']);?></li>
                    <li><?php echo Html::a('Galeri', ['galeri/index']);?></li>
                    <li><?php echo Html::a('Kontak', ['site/kontak']);?></li>
                </ul>
            </nav>
            <!-- / navigation -->
        </div>
        <!-- / container -->
    
    </header>
    <!-- / header -->
    
    <?php echo $content;?>

    <footer id="footer">
        <div class="container">
            <section>
                <article class="col-1">
                    <h3>Alamat</h3>
                    <ul>
                        <li class="address"><a href="#">Gedung Energi Lt. 2 (EN-201) <br>Kampus Politeknik Elektronika <br>Negeri Surabaya<br>Jl. Raya ITS - Kampus PENS Sukolilo, Surabaya 60111,<br> INDONESIA</a></li>
                        <li class="mail"><a href="#">himaenergi@gmail.com</a></li>
                        <li class="phone last"><a href="#">ComingSoon</a></li>
                    </ul>
                </article>
                <article class="col-2">
                    <h3>Navigation</h3>
                    <ul>
                        <li><?php echo Html::a('Profil', ['site/profil']);?></li>
                        <li><?php echo Html::a('Berita', ['berita/index']);?></li>
                        <li><?php echo Html::a('Agenda', ['agenda/index']);?></li>
                        <li><?php echo Html::a('Akademik', ['akademik/index']);?></li>
                        <li><?php echo Html::a('Galeri', ['galeri/index']);?></li>
                        <li><?php echo Html::a('Kontak', ['site/kontak']);?></li>
                    </ul>
                </article>
                <article class="col-3">
                    <h3>Media Sosial</h3>
                    <p>Dapatkan informasi seputar Hima Energi PENS melalui Media Sosial kami</p>
                    <ul>
                        <li class="facebook"><a target="_blank" href="https://www.facebook.com/HimaEnergi/">Facebook</a></li>
                        <li class="google-plus"><a target="_blank" href="https://line.com/spy0018L">@SPY0018L</a></li>
                        <li class="twitter"><a target="_blank" href="https://twitter.com/HimaEnergi">Twitter</a></li>
                        <li class="pinterest"><a target="_blank" href="https://instagram.com/himaenergipens">Instagram</a></li>
                    </ul>
                </article>
                <article class="col-4">
                    <h3>Newsletter</h3>
                    <p>Ingin mendapatkan berita secara realtime, berlangganan aja di website kami.</p>
                    <form action="#">
                        <input placeholder="Email address..." type="email">
                        <button type="submit">Subscribe</button>
                    </form>
                </article>
            </section>

            <p class="copy">Copyright 2017 Himpunan Mahasiswa Sistem Pembangkit Energi PENS. Designed by <a href="http://www.vandelaydesign.com/" title="Designed by Vandelay Design" target="_blank">Vandelay Design</a>. All rights reserved.</p>
        </div>
        <!-- / container -->
    </footer>
    <!-- / footer -->

    <div id="fancy">
        <h2>Kritik dan Saran</h2>
        <form action="#">
            <div class="left">
                <fieldset class="mail"><input placeholder="Alamat Email" type="text"></fieldset>
                <fieldset class="name"><input placeholder="Nama" type="text"></fieldset>
                <fieldset class="subject"><input placeholder="NRP" type="text"></fieldset>
            </div>
            <div class="right">
                <fieldset class="question"><textarea placeholder="Tuliskan kritik dan/atau saran anda disini"></textarea></fieldset>
            </div>
            <div class="btn-holder">
                <button class="btn" type="submit">Kirim</button>
            </div>
        </form>
    </div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>