backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/AgendaController.php
<?php

namespace frontend\controllers;

class AgendaController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionDetails()
    {
    	return $this->render('details');
    }

}

frontend/controllers/BeritaController.php
<?php

namespace frontend\controllers;

use Yii;

class BeritaController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionDetails()
    {
    	return $this->render('details');
    }

}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionProfil()
    {
        return $this->render('profil');
    }

    public function actionKontak()
    {
        return $this->render('kontak');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="divider"></div>

<div class="content">
    <div class="container">
        <div class="site-error">

            <h1><?= Html::encode($this->title) ?></h1>
            <div class="alert alert-danger">
                <?= nl2br(Html::encode($message)) ?>
            </div>
            <p>
                Halaman yang anda inginkan tidak ada. Kemungkinan anda salah memasukkan alamat.
            </p>
            <p>
                Silahkan menghubungi administrator jika kamu mendapatkan pesan error. Terimakasih.
            </p>
        </div>
  
    </div>
</div>

<br>
<br>

frontend/views/site/index.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
$this->title = 'HIMA ENERGI PENS';
?>
<div class="slider">
    <ul class="bxslider">
        <li>
            <div class="container">
                <div class="info">
                    <h2> Selamat Datang<br><span>HIMA ENERGI PENS</span></h2>
                    <?php echo Html::a('Checkout more details', ['site/profil']);?>
                </div>
            </div>
            <!-- / content -->
        </li>
        <li>
            <div class="container">
                <div class="info">
                    <h2>Berita <br><span>Kabar Terbaru</span></h2>
                    <?php echo Html::a('Checkout more details', ['berita/index']);?>
                </div>
            </div>
            <!-- / content -->
        </li>
        <li>
            <div class="container">
                <div class="info">
                    <h2>Agenda <br><span>Timeline Himpunan</span></h2>
                    <?php echo Html::a('Checkout more details', ['agenda/index']);?>
                </div>
            </div>
            <!-- / content -->
        </li>
    </ul>
    <div class="bg-bottom"></div>
</div>

<section class="posts">
    <div class="container">
        <article>
            <div class="pic"><img width="121" src="<?php echo Yii::getAlias('@depan');?>/tema/images/2.png" alt=""></div>
            <div class="info">
                <h3>Profil</h3>
                <p>
                    Sebuah wadah yang bersifat organisasi mahasiswa di lingkup program studi Sistem Pembangkitan Energi. Hima Energi merupakan himpunan mahasiswa ke tujuh yang ada dilingkup ormawa PENS dengan memiliki ciri khas warna coklat. <br>
                    <?php echo Html::a('Read more', ['site/profil'], ['class'=>'more']);?>
                </p> 
                     
            </div>
        </article>
        <article>
            <div class="pic"><img width="121" src="<?php echo Yii::getAlias('@depan');?>/tema/images/3.png" alt=""></div>
            <div class="info">
                <h3>Budaya</h3>
                <p>Berani dan kekeluargaan merupakan budaya yang dipegang erat oleh seluruh anggota Hima Energi. Berani mengungkapkan pendapat, ide, gagasa, dll serta bertanggung jawab dengan asas kekeluargaan merupakan implementasi dari budaya SPE.</p>
            </div>
        </article>
    </div>
    <!-- / container -->
</section>

<section class="news">
    <div class="container">
        <h2>BERITA TERBARU</h2>
        
        <article>
            <div class="pic"><img src="<?php echo Yii::getAlias('@depan');?>/tema/images/1.png" alt=""></div>
            <div class="info">
                <h4>Kampanye Debat Suksesi Hima Energi 2017<br/>Jilid II 1</h4>
                <p class="date">21 JUNI 2017, Admin</p>
                <p>Setelah dilaksanakannya Kampanye Debat Suksesi Hima Energi 2017 Jilid I pada tanggal 20 Juni 2017, Kampanye Debat Suksesi Hima Energi Jilid ke 2 dilaksanakan ditempat yang sama dengan mengusung tema "Peran dan Fungsi Ketua Himpunan Mahasiswa Energi PENS di lingkup KM PENS" </p>
                <?php echo Html::a('Read more', ['berita/details'], ['class'=>'more btn']);?>
            </div>
        </article>

        <article>
            <div class="pic"><img src="<?php echo Yii::getAlias('@depan');?>/tema/images/1.png" alt=""></div>
            <div class="info">
                <h4>Kampanye Debat Suksesi Hima Energi 2017<br/>Jilid II 2</h4>
                <p class="date">21 JUNI 2017, Admin</p>
                <p>Setelah dilaksanakannya Kampanye Debat Suksesi Hima Energi 2017 Jilid I pada tanggal 20 Juni 2017, Kampanye Debat Suksesi Hima Energi Jilid ke 2 dilaksanakan ditempat yang sama dengan mengusung tema "Peran dan Fungsi Ketua Himpunan Mahasiswa Energi PENS di lingkup KM PENS" </p>
                <?php echo Html::a('Read more', ['berita/details'], ['class'=>'more btn']);?>
            </div>
        </article>

        <article>
            <div class="pic"><img src="<?php echo Yii::getAlias('@depan');?>/tema/images/1.png" alt=""></div>
            <div class="info">
                <h4>Kampanye Debat Suksesi Hima Energi 2017<br/>Jilid II 3</h4>
                <p class="date">21 JUNI 2017, Admin</p>
                <p>Setelah dilaksanakannya Kampanye Debat Suksesi Hima Energi 2017 Jilid I pada tanggal 20 Juni 2017, Kampanye Debat Suksesi Hima Energi Jilid ke 2 dilaksanakan ditempat yang sama dengan mengusung tema "Peran dan Fungsi Ketua Himpunan Mahasiswa Energi PENS di lingkup KM PENS" </p>
                <?php echo Html::a('Read more', ['berita/details'], ['class'=>'more btn']);?>
            </div>
        </article>

        <article>
            <div class="pic"><img src="<?php echo Yii::getAlias('@depan');?>/tema/images/1.png" alt=""></div>
            <div class="info">
                <h4>Kampanye Debat Suksesi Hima Energi 2017<br/>Jilid II 4</h4>
                <p class="date">21 JUNI 2017, Admin</p>
                <p>Setelah dilaksanakannya Kampanye Debat Suksesi Hima Energi 2017 Jilid I pada tanggal 20 Juni 2017, Kampanye Debat Suksesi Hima Energi Jilid ke 2 dilaksanakan ditempat yang sama dengan mengusung tema "Peran dan Fungsi Ketua Himpunan Mahasiswa Energi PENS di lingkup KM PENS" </p>
                <?php echo Html::a('Read more', ['berita/details'], ['class'=>'more btn']);?>
            </div>
        </article>

        <div class="btn-holder">
            <?php echo Html::a('Read more', ['berita/index'], ['class'=>'blue btn']);?>
        </div>
    </div>
    <!-- / container -->
</section>

<section class="events">
    <div class="container">
        <h2>AGENDA</h2>
        <article>
            <div class="current-date">
                <p>Juni</p>
                <p class="date">02</p>
            </div>
            <div class="info">
                <p>Dies Natalis ke-29 Politeknik Elektronika Negeri Surabaya </p>
                <?php echo Html::a('Read more', ['agenda/details'], ['class'=>'more']);?>
            </div>
        </article>
        <article>
            <div class="current-date">
                <p>Juli</p>
                <p class="date">18</p>
            </div>
            <div class="info">
                <p>Musyawarah Pemilihan Ketua Hima Energi PENS<br/>Periode 2017/2018</p>
                <?php echo Html::a('Read more', ['agenda/details'], ['class'=>'more']);?>
            </div>
        </article>
        <article>
            <div class="current-date">
                <p>Juli</p>
                <p class="date">19</p>
            </div>
            <div class="info">
                <p>Serah Terima Jabatan Badan Pengurus Hima Energi PENS Periode 2016/2017 kepada Badan Pengurus Hima Energi PENS Periode 2017/2018</p>
                <?php echo Html::a('Read more', ['agenda/details'], ['class'=>'more']);?>
            </div>
        </article>
        <article>
            <div class="current-date">
                <p>Desember</p>
                <p class="date">29</p>
            </div>
            <div class="info">
                <p>3rd Anniversary of Hima Energi PENS</p>
                <?php echo Html::a('Read more', ['agenda/details'], ['class'=>'more']);?>
            </div>
        </article>
        <div class="btn-holder">
            <?php echo Html::a('Lihat Semua Agenda', ['agenda/index'], ['class'=>'btn blue']);?>
        </div>
    </div>
    <!-- / container -->
</section>

<div class="container">
    <a href="#fancy" class="info-request">
        <span class="holder">
            <span class="title">Kritik dan saran</span>
            <span class="text">Berikan kritik maupun saran anda untuk hima energi melalui website ini!</span>
        </span>
        <span class="arrow"></span>
    </a>
</div>

frontend/views/site/kontak.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
$this->title = 'Kontak | HIMA ENERGI PENS';
?>
<div class="divider"></div>

<div class="content">
    <div class="container">
        <div class="main-content">
            <div class="posts">
                <h1>Kontak Kami</h1>

                <h3><strong>Alamat</strong></h3>
                <p>
                    Gedung Energi Lt. 2 (EN-201) <br>
                    Kampus Politeknik Elektronika Negeri Surabaya <br>
                    Jl. Raya ITS - Kampus PENS Sukolilo, Surabaya 60111
                    INDONESIA
                </p>
                <hr>

                <h3><strong>Official Account</strong></h3>
                <p>
                    Facebook : HimaEnergi<br>
                    Line : @SPY0018L<br>
                    Twitter: HimaEnergi<br>
                    Instagram : himaenergipens         
                </p>
            </div>    
        </div>

        <aside id="sidebar">
            <div class="widget clearfix calendar">
                <div class="head">
                    <a class="prev" href="#"></a>
                    <a class="next" href="#"></a>
                    <h4><?php echo date('F'). ' ' . date('Y');?></h4>
                </div>
                <div class="table">
                    <table>
                        <tr>
                            <th class="col-1">Sen</th>
                            <th class="col-2">Sel</th>
                            <th class="col-3">Rab</th>
                            <th class="col-4">Kam</th>
                            <th class="col-5">Jum</th>
                            <th class="col-6">Sab</th>
                            <th class="col-7">Min</th>
                        </tr>
                        <tr>
                            <td class="col-1 disable"><div>26</div></td>
                            <td class="col-2 disable"><div>27</div></td>
                            <td class="col-3 disable"><div>28</div></td>
                            <td class="col-4 disable"><div>29</div></td>
                            <td class="col-5 disable"><div>30</div></td>
                            <td class="col-6"><div>1</div></td>
                            <td class="col-7"><div>2</div></td>
                        </tr>
                        <tr>
                            <td class="col-1"><div>3</div></td>
                            <td class="col-2"><div>4</div></td>
                            <td class="col-3 archival"><div>5</div></td>
                            <td class="col-4"><div>6</div></td>
                            <td class="col-5"><div>7</div></td>
                            <td class="col-6"><div>8</div></td>
                            <td class="col-7"><div>9</div></td>
                        </tr>
                        <tr>
                            <td class="col-1"><div>10</div></td>
                            <td class="col-2 upcoming"><div><div class="tooltip"><div class="holder">
                                <h4>Omnis iste natus error sit voluptatem dolor</h4>
                                <p class="info-line"><span class="time">10:30 AM</span><span class="place">Lincoln High School</span></p>
                                <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident similique.</p>
                            </div></div>11</div></td>
                            <td class="col-3"><div>12</div></td>
                            <td class="col-4 upcoming"><div><div class="tooltip"><div class="holder">
                                <h4>Omnis iste natus error sit voluptatem dolor</h4>
                                <p class="info-line"><span class="time">10:30 AM</span><span class="place">Lincoln High School</span></p>
                                <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident similique.</p>
                            </div></div>12</div></td>
                            <td class="col-5"><div>13</div></td>
                            <td class="col-6"><div>14</div></td>
                            <td class="col-7"><div>15</div></td>
                        </tr>
                        <tr>
                            <td class="col-1"><div>16</div></td>
                            <td class="col-2"><div>17</div></td>
                            <td class="col-3"><div>18</div></td>
                            <td class="col-4"><div>19</div></td>
                            <td class="col-5 upcoming"><div><div class="tooltip"><div class="holder">
                                <h4>Omnis iste natus error sit voluptatem dolor</h4>
                                <p class="info-line"><span class="time">10:30 AM</span><span class="place">Lincoln High School</span></p>
                                <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident similique.</p>
                            </div></div>20</div></td>
                            <td class="col-6"><div>21</div></td>
                            <td class="col-7"><div>22</div></td>
                        </tr>
                        <tr>
                            <td class="col-1"><div>23</div></td>
                            <td class="col-2 upcoming"><div><div class="tooltip"><div class="holder">
                                <h4>Omnis iste natus error sit voluptatem dolor</h4>
                                <p class="info-line"><span class="time">10:30 AM</span><span class="place">Lincoln High School</span></p>
                                <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident similique.</p>
                            </div></div>24</div></td>
                            <td class="col-3"><div>25</div></td>
                            <td class="col-4"><div>26</div></td>
                            <td class="col-5"><div>27</div></td>
                            <td class="col-6"><div>28</div></td>
                            <td class="col-7"><div>29</div></td>
                        </tr>
                        <tr>
                            <td class="col-1"><div>30</div></td>
                            <td class="col-2 upcoming"><div><div class="tooltip"><div class="holder">
                                <h4>Omnis iste natus error sit voluptatem dolor</h4>
                                <p class="info-line"><span class="time">10:30 AM</span><span class="place">Lincoln High School</span></p>
                                <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident similique.</p>
                            </div></div>31</div></td>
                            <td class="col-3"><div>1</div></td>
                            <td class="col-4 disable"><div>2</div></td>
                            <td class="col-5 disable"><div>3</div></td>
                            <td class="col-6 disable"><div>4</div></td>
                            <td class="col-7 disable"><div>5</div></td>
                        </tr>
                    </table>
                </div>
            </div>
        </aside>

    </div>
</div>

<div class="container">
    <a href="#fancy" class="info-request">
        <span class="holder">
            <span class="title">Kritik dan saran</span>
            <span class="text">Berikan kritik maupun saran anda untuk hima energi melalui website ini!</span>
        </span>
        <span class="arrow"></span>
    </a>
</div>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div style="color:#999;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                </div>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/profil.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
$this->title = 'Profil | HIMA ENERGI PENS';
?>
<div class="divider"></div>

<style type="text/css">
    #gambar-kiri{
        float: left;
        margin: 20px;
        padding-right: 20px; 
    }
    #gambar-kanan{
        float: right;
        margin: 20px;
        padding-left: 20px; 
    }
</style>

<div class="content">
    <div class="container">
        <div class="posts">
            <h1>Sejarah</h1>
            <img id="gambar-kiri" src="<?php echo Yii::getAlias('@depan/tema/images/logo.png');?>">
            <p>
                Sejarah Hima Energi Himpunan Mahasiswa Sistem Pembangkit Energi yang disebut menjadi HIMA ENERGI adalah suatu organisasi kemahasiswaan yang berdiri di Politeknik Elektronika Negeri Surabaya.Program Study Sistem Pembangkit Energi didirakan pada tahun 2011, mahasiswa SPE angkatan pertama menjadi mahasiswa baru dengan Prodi yang baru juga dalam lingkungan kampus PENS dan tentunya lingkup KM PENS. Hal ini menimbulkan sebuah pertanyaan baru bagaimana dengan proses pengembangan mahasiswa baru ini, dikarenakan dari segi keprofesian Himpunan Mahasiswa Teknik Elektro Industri (Hima Elin) paling mendekati dengan Sistem Pembangkit Energi maka diputuskan bahwa mahasiswa SPE dinaungi oleh Hima Elin.
            </p>
            <br>
            <p>
                Bertepatan pada tahun 2012 diadakan pergantian sistem didalam manajemen kampus dengan munculnya departemen-departemen yang menaungi Prodi. Dengan pertimbangan kesesuaian secara materi pendidikan maka diputuskan  Prodi SPE dan  Prodi Teknik Mekatronika berada dalam satu naungan departemen, sehingga pengembangan kemahasiswaan SPE dialihkan ke Himpunan Mahasiswa Teknik Mekatronika (Hima Meka).
            </p>
            <br>
            <img id="gambar-kanan" src="<?php echo Yii::getAlias('@depan/tema/images/logo.png');?>">
            <p>
                Seiring berjalannya waktu, mahasiswa SPE mulai berkembang dan mengetahui akan ranah pengembangan yang lebih sesuai dengan keprofesiannya. Maka dari itu mahasiswa SPE mengusulkan untuk dilakukan  pembentukan Hima Energi. Namun Karena dari pihak Hima Meka merasa bahwa kesiapan dari mahasiswa SPE untuk membentuk sebuah himpunan masih kurang maka dari pihak BEM melalui Kementrian Dalam Negeri melakukan mediasi diantara kedua belah pihak. Pada akhirnya disepakati untuk membentuk Badan Semi Otonom yang lebih dikenal dengan BSO SPE PENS yang berfungsi untuk mewadahi mahasiswa SPE dalam mengembangkan minat dan bakatnya dalam berorganisasi dan untuk mempersiapkan segala kebutuhan untuk mendirikan sebuah Himpunan.
            </p>
            <br>
            <p>
                Pada akhirnya, dengan berdirinya BSO SPE PENS mahasiswa SPE lebih aktif dalam melakukan propaganda dan menghimpun dukungan dari semua elemen KM untuk mendirikan sebuah himpunan. Dan akhirnya setelah seluruh kelengkapan sebuah Himpunan terpenuhi dan pengakuan dari seluruh elemen KM PENS telah didapatkan,  tepat pada tanggal 29 Desember 2014 berdirilah secara resmi Himpunan Mahasiswa Sistem Pembangkit Energi sesuai dengan SK Direktur No.4297.01/PI.14/KM/2014.
            </p>
        </div>  
    </div>
</div>

<div class="container">
    <a href="#fancy" class="info-request">
        <span class="holder">
            <span class="title">Kritik dan saran</span>
            <span class="text">Berikan kritik maupun saran anda untuk hima energi melalui website ini!</span>
        </span>
        <span class="arrow"></span>
    </a>
</div>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>